### ISSUE TITLE
[BUG] IdeaRS.ConnectionLink.ConnectionLink.TestValidCSSInIDEADatabase

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom#17]
# Unable to attach a debugger 
The same issue was happening in version 8, then it was fixed in version 9.0 (and also 10 and 10.1), but now, it is running in v 20.0.

**To Reproduce**
Attach Visual Studio to any process that calls:
```csharp 
IdeaRS.ConnectionLink.ConnectionLink.TestValidCSSInIDEADatabase(IList<string> testedNames, out IList<string> notValidNames)
```
**Expected behavior**
We are using ConnectionLink because we need to get information about whether a section name exists in the MPRL.
It would also be fine for us to do the same with material name.
_I need to attach a debugger in order to debug our plugin._

![image](https://user-images.githubusercontent.com/66376954/83997869-b0b72000-a95f-11ea-9a8b-11c4b63bf0c2.png)

**Desktop:**
 - OS: Windows 10 Pro-1909
 - IOM Version 20.0,
 - IdeaStatiCa Version 20.0.77.57142

**Additional context**
I have talked about that with @tLuber72

**Comment by mpospisil** [comment]
ConnectionLink  is obsolete. I would suggest to use our new API - see example :

https://github.com/idea-statica/ccm-examples

whe you can find how to get list of all materials and cross-sections in a ccm project or MPRL. The new API solves problems caused by our anti debug protection as well as licenses.
