### ISSUE TITLE
[BUG] Set Weld Thickness and Type for Beam to Beam Cut

### ISSUE THREAD

**Issue by NathanlGG** [idea-statica/iom#28]
Hi, I am trying to specify weld type and thickness for a beam/beam cut but it does not seem to get read into IdeaStatica on opening the file. 

Should this be working or is the functionality not available yet?

![image](https://user-images.githubusercontent.com/45442361/111562376-3539a780-87ea-11eb-8779-975ed501937c.png)

[Beam by Beam Cut.zip](https://github.com/idea-statica/iom/files/6160820/Beam.by.Beam.Cut.zip)

 - OS: Windows 10
 - IOM Version 21.0.14
 - IdeaStatiCa Version 20.1.5115.1

**Comment by vojtech-chalupa** [comment]
Hello, this has been fixed and should work on the latest release 21.0.0.3277.
However, in order to get the expected result, please use the correct unit (0.008 instead of 8 for the weld size), and also specify a "Surface" cut instead of "Bounding box" Method in your IOM:

![image](https://user-images.githubusercontent.com/73105487/119135172-59aa3e00-ba3e-11eb-9cdf-806f19749df1.png)
